sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

install:
  - docker-compose run --rm php composer install -n
  - docker-compose run --rm php ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - docker-compose build tests

script:
  - docker-compose run --rm tests

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true