version: '2'
services:
  tests:
    build: .
    image: keboola/google-bigquery-extractor
    volumes:
      - .:/code
    working_dir: /code
    command: sh -c 'composer install && php vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php . && php vendor/bin/phpunit'
    tty: true
    stdin_open: true
    environment:
      - KBC_CONFIGID=extractor-test
      - KBC_DATADIR=/tmp/extractor
      - KBC_RUNID=987.654.321
      - BIGQUERY_EXTRACTOR_ACCESS_TOKEN_JSON
      - BIGQUERY_EXTRACTOR_APP_KEY
      - BIGQUERY_EXTRACTOR_APP_SECRET
      - BIGQUERY_EXTRACTOR_CLOUD_STORAGE_BUCKET
      - BIGQUERY_EXTRACTOR_BILLABLE_GOOGLE_PROJECT
      - BIGQUERY_EXTRACTOR_NONBILLABLE_GOOGLE_PROJECT
