version: '2'
services:
  tests:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    entrypoint: "./phpunit.sh"
    tty: true
    stdin_open: true
    environment:
      KBC_CONFIGID: "extractor-test"
      KBC_DATADIR: /tmp/extractor
      KBC_RUNID: 987.654.321
      ENV_BIGQUERY_EXTRACTOR_ACCESS_TOKEN_JSON: $ENV_BIGQUERY_EXTRACTOR_ACCESS_TOKEN_JSON
      ENV_BIGQUERY_EXTRACTOR_APP_KEY: $ENV_BIGQUERY_EXTRACTOR_APP_KEY
      ENV_BIGQUERY_EXTRACTOR_APP_SECRET: $ENV_BIGQUERY_EXTRACTOR_APP_SECRET
      ENV_BIGQUERY_EXTRACTOR_CLOUD_STORAGE_BUCKET: $ENV_BIGQUERY_EXTRACTOR_CLOUD_STORAGE_BUCKET
      ENV_BIGQUERY_EXTRACTOR_BILLABLE_GOOGLE_PROJECT: $ENV_BIGQUERY_EXTRACTOR_BILLABLE_GOOGLE_PROJECT
      ENV_BIGQUERY_EXTRACTOR_NONBILLABLE_GOOGLE_PROJECT: $ENV_BIGQUERY_EXTRACTOR_NONBILLABLE_GOOGLE_PROJECT

  php:
    image: keboola/docker-php56-all-db
    volumes:
        - .:/code
    working_dir: /code