#!/usr/bin/env bash

export ENV_BIGQUERY_EXTRACTOR_ACCESS_TOKEN_JSON="" 
export ENV_BIGQUERY_EXTRACTOR_APP_KEY=""
export ENV_BIGQUERY_EXTRACTOR_APP_SECRET=""
export ENV_BIGQUERY_EXTRACTOR_CLOUD_STORAGE_BUCKET=""
export ENV_BIGQUERY_EXTRACTOR_BILLABLE_GOOGLE_PROJECT=""
export ENV_BIGQUERY_EXTRACTOR_NONBILLABLE_GOOGLE_PROJECT=""
